apiVersion: apps/v1
kind: Deployment
metadata:
  name: kulonut-fe-vizsgaremek
  labels:
    app.kubernetes.io/name: kulonut-vizsgaremek
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kulonut-fe-vizsgaremek
  template:
    metadata:
      labels:
        app: kulonut-fe-vizsgaremek
    spec:
      containers:
        - name: httpd-container
          image: ghcr.io/megadrive88/kulonut-fe-vizsgaremek:1775395418
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr-auth-token

---

apiVersion: v1
kind: Service
metadata:
  name: kulonut-fe-vizsgaremek-service
spec:
  type: LoadBalancer   # Use NodePort if testing locally
  selector:
    app: kulonut-fe-vizsgaremek
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80